### ISSUE TITLE
move github actions to micromamba action

### ISSUE THREAD

**Issue by CagtayFabry** [BAMWelDX/weldx-widgets#111]
Use micromamba setup isntead of pip install for speedup (e.g. similar to weldx setup)

```yaml
      - uses: CagtayFabry/pydeps2env@main
        with:
          file: 'pyproject.toml'
          channels: 'conda-forge defaults'
          extras: 'test vis media'
          setup_requires: 'include'

      - name: Setup Conda Environment
        uses: mamba-org/setup-micromamba@v1.4.4
        with:
          environment-file: ./environment.yml
          environment-name: weldx
          init-shell: >-
            bash
            powershell
          cache-environment: true
          create-args: >-
            python=${{ matrix.py }}
            wheel
            pip
```
